const CART_ACTIONS = {
    LOAD_CART: 'LOAD_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    UPDATE_TO_CART: 'UPDATE_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    EMPTY_CART: 'EMPTY_CART',
    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
    ACTION_CART_SUCCESS: 'ACTION_CART_SUCCESS',
    ACTION_CART_FAILURE: 'ACTION_CART_FAILURE',
    ACTION_CART_REQUEST: 'ACTION_CART_REQUEST',
    FETCH_CART_ITEMS: 'FETCH_CART_ITEMS',
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    SET_DB_CART_ITEMS: 'SET_DB_CART_ITEMS',
    SAVE_DB_CART_ITEMS: 'SAVE_DB_CART_ITEMS',
}

export default CART_ACTIONS