const WISH_LIST_ACTIONS = {
    ADD_TO_WISH_LIST: 'ADD_TO_WISH_LIST',
    UPDATE_TO_WISH_LIST: 'UPDATE_TO_WISH_LIST',
    REMOVE_FROM_WISH_LIST: 'REMOVE_FROM_WISH_LIST',
    EMPTY_WISH_LIST: 'EMPTY_WISH_LIST',
    ACTION_WISH_LIST_SUCCESS: 'ACTION_WISH_LIST_SUCCESS',
    ACTION_WISH_LIST_FAILURE: 'ACTION_WISH_LIST_FAILURE',
    ACTION_WISH_LIST_REQUEST: 'ACTION_WISH_LIST_REQUEST',
    FETCH_WISH_LIST_ITEMS: 'FETCH_WISH_LIST_ITEMS',
    SET_WISH_LIST_ITEMS: 'SET_WISH_LIST_ITEMS',
}

export default WISH_LIST_ACTIONS