const LOGIN_ACTIONS = {
    LOGIN_CUSTOMER_INFO: 'LOGIN_CUSTOMER_INFO',
    ACTION_LOGIN_SUCCESS: 'ACTION_LOGIN_SUCCESS',
    ACTION_LOGIN_FAILURE: 'ACTION_LOGIN_FAILURE',
    ACTION_LOGIN_GOOGLE: 'ACTION_LOGIN_GOOGLE',
    ACTION_GET_CREDENTIALS: 'ACTION_GET_CREDENTIALS',
    ACTION_TOKEN_REQUEST: 'ACTION_VERIFY_REQUEST',
    ACTION_VERIFY_FAILURE: 'ACTION_VERIFY_FAILURE',
    FETCH_TOKEN_SUCCESS: 'FETCH_TOKEN_SUCCESS',
    PERMISSION_REQUEST: 'PERMISSION_REQUEST',
    PERMISSION_SUCCESS: 'PERMISSION_SUCCESS',
    PERMISSION_FAILURE: 'PERMISSION_FAILURE',
    PASSWORD_RECOVER_SUCCESS: 'PASSWORD_RECOVER_SUCCESS',
    PASSWORD_RECOVER_FAILURE: 'PASSWORD_RECOVER_FAILURE'
}

export default LOGIN_ACTIONS