const PRODUCT_ACTIONS = {
    ACTION_PRODUCTS_REQUEST: 'ACTION_PRODUCTS_REQUEST',
    ACTION_PRODUCTS_FAILURE: 'ACTION_PRODUCTS_FAILURE',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_STOCK: 'ADD_STOCK',
    FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_A_PRODUCT_SUCCESS: 'FETCH_A_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    CLEAR_PRODUCT_SUCCESS: 'CLEAR_PRODUCT_SUCCESS',
    FETCH_PRODUCT_ID_SUCCESS: 'FETCH_PRODUCT_ID_SUCCESS',
    FETCH_PRODUCT_CATEGORY_SUCCES: 'FETCH_PRODUCT_CATEGORY_SUCCES',
    CLEAR_FILTER_CATEGORY: 'CLEAR_FILTER_CATEGORY'
}

export default PRODUCT_ACTIONS